### ISSUE TITLE
Warning message on Wordpress 4.4RC

### ISSUE THREAD

**Issue by damiele** [chargebee/chargebee-wordpress-plugin#2]
Hi, by protecting a page (while in testing on a staging server) I get this message (it appears like I'm on debug mode, but I'm not):

Warning: substr() expects parameter 3 to be long, string given in /mywebsite/wp-content/plugins/chargebee/chargebee.php on line 423

something I could do to stop this?

Thank you!
Daniele

**Comment by damiele** [comment]
I reverted my installation to 4.3.1 and the issue persist.

Thank you!
Daniele

**Comment by hellokps** [comment]
Hi , Could you set the  "Allowed Characters"   in the chargebee plugin settings to a numerical value such as 150 and let us know if the issue persists.

thanks and regards,
-kps-

**Comment by damiele** [comment]
Hi, thank you for your support, I can confirm the "warning" message disappeared.

Should I stay with "150"?

Thank you, have a great day!
Daniele

**Comment by saravana-cb** [comment]
Hi,
No. You can give more than 150. We asked you to give numerical value in the field like "150" and not to go with alphabets.
